# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM-Ascend project

INDEX_CAPACITY = 128 * 1024
RESIDENT_SLOTS = 8 * 1024
REPLACEABLE_SLOTS = 2 * 1024
LOOKUP_SLOTS = RESIDENT_SLOTS + REPLACEABLE_SLOTS
QUERY_WIDTH = 2 * 1024
FREE_HEAD_STRIDE = 16
FALLBACK_SENTINEL = LOOKUP_SLOTS
