# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM-Ascend project

DSA_SPARSE_INDEX_CAPACITY = 128 * 1024
DSA_SPARSE_RESIDENT_SLOT_COUNT = 8 * 1024
DSA_SPARSE_FREE_SLOT_COUNT = 2 * 1024
DSA_SPARSE_LOOKUP_SLOT_COUNT = (
    DSA_SPARSE_RESIDENT_SLOT_COUNT + DSA_SPARSE_FREE_SLOT_COUNT
)
DSA_SPARSE_QUERY_WIDTH = 2 * 1024
DSA_SPARSE_FREE_HEAD_STRIDE = 16
